name: muscle_builder_diet_planner
description: "Muscle Builder & Diet Planner - Premium Offline Fitness & Diet Planner App"
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
